# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\tinventory\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\"\x9b\x02\n\x04\x42ook\x12\x11\n\x04ISBN\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05title\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06\x61uthor\x18\x03 \x01(\tH\x02\x88\x01\x01\x12*\n\x05genre\x18\x04 \x01(\x0e\x32\x16.inventory.Book.genresH\x03\x88\x01\x01\x12,\n\x0epublishingYear\x18\x05 \x01(\x0b\x32\x0f.inventory.DateH\x04\x88\x01\x01\"B\n\x06genres\x12\x0b\n\x07\x46\x41NTASY\x10\x00\x12\x0c\n\x08\x43LASSICS\x10\x01\x12\t\n\x05SCIFI\x10\x02\x12\t\n\x05HUMOR\x10\x03\x12\x07\n\x03WAR\x10\x04\x42\x07\n\x05_ISBNB\x08\n\x06_titleB\t\n\x07_authorB\x08\n\x06_genreB\x11\n\x0f_publishingYear\"\xd1\x01\n\rInventoryItem\x12\x1c\n\x0finventoryNumber\x18\x01 \x01(\x05H\x01\x88\x01\x01\x12\x1c\n\x01\x62\x18\x02 \x01(\x0b\x32\x0f.inventory.BookH\x00\x12\x36\n\x06status\x18\x03 \x01(\x0e\x32!.inventory.InventoryItem.statusesH\x02\x88\x01\x01\"$\n\x08statuses\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x42\x07\n\x05\x62ooksB\x12\n\x10_inventoryNumberB\t\n\x07_statusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATE._serialized_start=28
  _DATE._serialized_end=76
  _BOOK._serialized_start=79
  _BOOK._serialized_end=362
  _BOOK_GENRES._serialized_start=237
  _BOOK_GENRES._serialized_end=303
  _INVENTORYITEM._serialized_start=365
  _INVENTORYITEM._serialized_end=574
  _INVENTORYITEM_STATUSES._serialized_start=498
  _INVENTORYITEM_STATUSES._serialized_end=534
# @@protoc_insertion_point(module_scope)
