# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import library_pb2 as library__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\tinventory\x1a\rlibrary.proto\"@\n\x11\x43reateBookRequest\x12\"\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0f.inventory.BookH\x00\x88\x01\x01\x42\x07\n\x05_book\"A\n\x12\x43reateBookResponse\x12\"\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0f.inventory.BookH\x00\x88\x01\x01\x42\x07\n\x05_book\",\n\x0eGetBookRequest\x12\x11\n\x04\x62ook\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_book\">\n\x0fGetBookResponse\x12\"\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0f.inventory.BookH\x00\x88\x01\x01\x42\x07\n\x05_book2\xa3\x01\n\x10InventoryService\x12K\n\nCreateBook\x12\x1c.inventory.CreateBookRequest\x1a\x1d.inventory.CreateBookResponse\"\x00\x12\x42\n\x07GetBook\x12\x19.inventory.GetBookRequest\x1a\x1a.inventory.GetBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOOKREQUEST._serialized_start=44
  _CREATEBOOKREQUEST._serialized_end=108
  _CREATEBOOKRESPONSE._serialized_start=110
  _CREATEBOOKRESPONSE._serialized_end=175
  _GETBOOKREQUEST._serialized_start=177
  _GETBOOKREQUEST._serialized_end=221
  _GETBOOKRESPONSE._serialized_start=223
  _GETBOOKRESPONSE._serialized_end=285
  _INVENTORYSERVICE._serialized_start=288
  _INVENTORYSERVICE._serialized_end=451
# @@protoc_insertion_point(module_scope)
